server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 1q2w3e4r5t
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
